Repository helidon-io/helidon-examples, pull requests merged in 2024-08, with the labels that each got.

#63 4.x: Updates versions of beans.xml resources to 4.0
  examples/integrations/cdi/datasource-hikaricp-h2/src/main/resources/META-INF/beans.xml
  examples/integrations/cdi/datasource-hikaricp-mysql/src/main/resources/META-INF/beans.xml
  examples/integrations/cdi/datasource-hikaricp/src/main/resources/META-INF/beans.xml
  examples/integrations/cdi/jpa/src/main/resources/META-INF/beans.xml
  examples/integrations/cdi/pokemons/src/main/resources/META-INF/beans.xml
  examples/integrations/micrometer/mp/src/main/resources/META-INF/beans.xml
  examples/integrations/micronaut/data/src/main/resources/META-INF/beans.xml
  examples/integrations/microstream/greetings-mp/src/main/resources/META-INF/beans.xml
  examples/integrations/oci/atp-cdi/src/main/resources/META-INF/beans.xml
  examples/integrations/oci/objectstorage-cdi/src/main/resources/META-INF/beans.xml
  examples/integrations/oci/vault-cdi/src/main/resources/META-INF/beans.xml
  examples/integrations/vault/hcp-cdi/src/main/resources/META-INF/beans.xml
  examples/jbatch/src/main/resources/META-INF/beans.xml
  examples/messaging/jms-websocket-mp/src/main/resources/META-INF/beans.xml
  examples/messaging/kafka-websocket-mp/src/main/resources/META-INF/beans.xml
  examples/messaging/oracle-aq-websocket-mp/src/main/resources/META-INF/beans.xml
  examples/messaging/weblogic-jms-mp/src/main/resources/META-INF/beans.xml
  examples/metrics/filtering/mp/src/main/resources/META-INF/beans.xml
  examples/microprofile/bean-validation/src/main/resources/META-INF/beans.xml
  examples/microprofile/cors/src/main/resources/META-INF/beans.xml
  examples/microprofile/graphql/src/main/resources/META-INF/beans.xml
  examples/microprofile/hello-world-explicit/src/main/resources/META-INF/beans.xml
  examples/microprofile/hello-world-implicit/src/main/resources/META-INF/beans.xml
  examples/microprofile/idcs/src/main/resources/META-INF/beans.xml
  examples/microprofile/lra/src/main/resources/META-INF/beans.xml
  examples/microprofile/messaging-sse/src/main/resources/META-INF/beans.xml
  examples/microprofile/multipart/src/main/resources/META-INF/beans.xml
  examples/microprofile/multiport/src/main/resources/META-INF/beans.xml
  examples/microprofile/oci-tls-certificates/src/main/resources/META-INF/beans.xml
  examples/microprofile/oidc/src/main/resources/META-INF/beans.xml
  examples/microprofile/openapi/src/main/resources/META-INF/beans.xml
  examples/microprofile/security/src/main/resources/META-INF/beans.xml
  examples/microprofile/static-content/src/main/resources/META-INF/beans.xml
  examples/microprofile/telemetry/greeting/src/main/resources/META-INF/beans.xml
  examples/microprofile/telemetry/secondary/src/main/resources/META-INF/beans.xml
  examples/microprofile/tls/src/main/resources/META-INF/beans.xml
  examples/microprofile/websocket/src/main/resources/META-INF/beans.xml
  examples/quickstarts/helidon-quickstart-mp/src/main/resources/META-INF/beans.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/src/main/resources/META-INF/beans.xml
  examples/security/attribute-based-access-control/src/main/resources/META-INF/beans.xml
  examples/todo-app/backend/src/main/resources/META-INF/beans.xml
Labels: OCA Verified, 4.x

#64 Update parent pom relative path.
  pom.xml
Labels: OCA Verified, 4.x

#67 2.x: Update readmes
  CONTRIBUTING.md
  README.md
Labels: OCA Verified, 2.x

#66 3.x: Update readmes
  CONTRIBUTING.md
  README.md
Labels: OCA Verified, 3.x

#65 New MP gRPC end-to-end example that uses gRPC proxy-based API
  examples/microprofile/grpc/README.md
  examples/microprofile/grpc/pom.xml
  examples/microprofile/grpc/src/main/java/io/helidon/examples/microprofile/grpc/StringService.java
  examples/microprofile/grpc/src/main/java/io/helidon/examples/microprofile/grpc/StringServiceClient.java
  examples/microprofile/grpc/src/main/java/io/helidon/examples/microprofile/grpc/package-info.java
  examples/microprofile/grpc/src/main/proto/strings.proto
  examples/microprofile/grpc/src/main/resources/META-INF/beans.xml
  examples/microprofile/grpc/src/main/resources/application.yaml
  examples/microprofile/grpc/src/main/resources/client.p12
  examples/microprofile/grpc/src/main/resources/logging.properties
  examples/microprofile/grpc/src/main/resources/server.p12
  examples/microprofile/grpc/src/test/java/io/helidon/examples/microprofile/grpc/StringServiceTest.java
  examples/microprofile/pom.xml
Labels: OCA Verified, 4.x, grpc

#77 4.x webserver rate limit example
  examples/webserver/pom.xml
  examples/webserver/ratelimit/README.md
  examples/webserver/ratelimit/pom.xml
  examples/webserver/ratelimit/src/main/java/io/helidon/examples/webserver/ratelimit/Main.java
  examples/webserver/ratelimit/src/main/java/io/helidon/examples/webserver/ratelimit/SleepService.java
  examples/webserver/ratelimit/src/main/java/io/helidon/examples/webserver/ratelimit/package-info.java
  examples/webserver/ratelimit/src/main/resources/application.yaml
  examples/webserver/ratelimit/src/main/resources/logging.properties
  examples/webserver/ratelimit/src/test/java/io/helidon/examples/webserver/ratelimit/MainTest.java
Labels: OCA Verified, 4.x

#80 4.x owasp script update
  etc/scripts/owasp-dependency-check.sh
  pom.xml
Labels: OCA Verified

#82 Fix update version awk shebang
  .github/workflows/validate.yml
  etc/scripts/checkstyle.sh
  etc/scripts/copyright.sh
  etc/scripts/dependency-check.sh
  etc/scripts/prime-build.sh
  etc/scripts/release.sh
  etc/scripts/shellcheck.sh
  etc/scripts/spotbugs.sh
  etc/scripts/update-version.awk
Labels: OCA Verified

#86 4.x: Fix update-version script to update helidon-version in build.gradle
  etc/scripts/update-version.sh
Labels: OCA Verified, 4.x
