Repository helidon-io/helidon-examples, pull requests merged in 2024-04, with the labels that each got.

#36 /webclient/standalone example builds OK but running the separate client as in the README.md fails
  examples/webclient/standalone/src/main/java/io/helidon/examples/webclient/standalone/ServerMain.java
Labels: OCA Verified

#40 2.x: Remove ToDo example
  examples/pom.xml
  examples/todo-app/README.md
  examples/todo-app/backend/pom.xml
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/DbService.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/JaxRsBackendResource.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/Main.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/Todo.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/package-info.java
  examples/todo-app/backend/src/main/resources/META-INF/beans.xml
  examples/todo-app/backend/src/main/resources/application.yaml
  examples/todo-app/backend/src/main/resources/logging.properties
  examples/todo-app/backend/src/test/java/io/helidon/demo/todos/backend/BackendTests.java
  examples/todo-app/backend/src/test/resources/test-application.yaml
  examples/todo-app/cassandra/Dockerfile
  examples/todo-app/cassandra/startup.sh
  examples/todo-app/frontend/pom.xml
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/BackendServiceClient.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/Main.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/TodoService.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/package-info.java
  examples/todo-app/frontend/src/main/resources/WEB/css/styles.css
  examples/todo-app/frontend/src/main/resources/WEB/index.html
  examples/todo-app/frontend/src/main/resources/WEB/js/app.js
  examples/todo-app/frontend/src/main/resources/application.yaml
  examples/todo-app/frontend/src/main/resources/logging.properties
  examples/todo-app/frontend/src/test/java/io/helidon/demo/todos/frontend/TodoServiceTest.java
  examples/todo-app/frontend/src/test/resources/application-test.yaml
  examples/todo-app/pom.xml
Labels: OCA Verified, 2.x

#42 3.x: Remove dependencies on jakarta.activation-api
  examples/jbatch/pom.xml
  examples/messaging/weblogic-jms-mp/pom.xml
  examples/microprofile/http-status-count-mp/pom.xml
Labels: OCA Verified, 3.x

#41 2.x: Remove dependency on jakarta.activation-api
  examples/istio/helidon-config/pom.xml
  examples/istio/helidon-jpa/pom.xml
  examples/jbatch/pom.xml
  examples/microprofile/http-status-count-mp/pom.xml
Labels: OCA Verified

#45 3.x: Fix #43: streaming example fails to start
  examples/webserver/streaming/README.md
  examples/webserver/streaming/large-file.bin
  examples/webserver/streaming/pom.xml
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/Main.java
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/ServerFileReader.java
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/ServerFileWriter.java
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/StreamingService.java
  examples/webserver/streaming/src/test/java/io/helidon/webserver/examples/streaming/MainTest.java
Labels: OCA Verified

#46 2.x: Fix #44: streaming example fails to start
  examples/webserver/streaming/README.md
  examples/webserver/streaming/large-file.bin
  examples/webserver/streaming/pom.xml
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/Main.java
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/ServerFileReader.java
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/ServerFileWriter.java
  examples/webserver/streaming/src/main/java/io/helidon/webserver/examples/streaming/StreamingService.java
  examples/webserver/streaming/src/test/java/io/helidon/webserver/examples/streaming/MainTest.java
Labels: OCA Verified, 2.x

#48 3.x: Handle TMPDIR not being set
  etc/scripts/updatehelidonversion.sh
Labels: OCA Verified
