Repository helidon-io/helidon-examples, pull requests merged in 2024-06, with the labels that each got.

#52 3.x: Cleanup of owasp scan and some pr validation checks
  etc/dependency-check-suppression.xml
  etc/scripts/owasp-dependency-check.sh
  examples/pom.xml
  pom.xml
Labels: OCA Verified, 3.x

#55 [dev-2.x] project version update
  examples/istio/helidon-config/pom.xml
  examples/istio/helidon-jpa/pom.xml
  examples/messaging/jms-websocket-mp/pom.xml
  examples/messaging/jms-websocket-se/pom.xml
  examples/messaging/kafka-websocket-mp/pom.xml
  examples/messaging/kafka-websocket-se/pom.xml
  examples/messaging/oracle-aq-websocket-mp/pom.xml
  examples/metrics/http-status-count-se/pom.xml
  examples/microprofile/http-status-count-mp/pom.xml
  examples/openapi-tools/quickstart-mp/mp-client/pom.xml
  examples/openapi-tools/quickstart-mp/mp-server/pom.xml
  examples/openapi-tools/quickstart-se/se-client/pom.xml
Labels: OCA Verified, 2.x

#54 [dev-3.x] project versions update
  examples/integrations/cdi/datasource-hikaricp/pom.xml
  examples/openapi-tools/quickstart-mp/mp-client/pom.xml
  examples/openapi-tools/quickstart-mp/mp-server/pom.xml
  examples/openapi-tools/quickstart-se/se-client/pom.xml
  examples/openapi-tools/quickstart-se/se-server/pom.xml
  examples/todo-app/backend/pom.xml
  examples/todo-app/frontend/pom.xml
Labels: OCA Verified, 3.x

#56 [dev-4.x] Properties alignment to README.md
  examples/security/basic-auth-with-static-content/src/main/java/io/helidon/examples/security/basicauth/BasicExampleBuilderMain.java
  examples/security/basic-auth-with-static-content/src/main/java/io/helidon/examples/security/basicauth/BasicExampleConfigMain.java
  examples/security/basic-auth-with-static-content/src/main/resources/WEB/index.html
  examples/security/webserver-digest-auth/src/main/java/io/helidon/examples/security/digest/DigestExampleBuilderMain.java
  examples/security/webserver-digest-auth/src/main/java/io/helidon/examples/security/digest/DigestExampleConfigMain.java
  examples/webserver/protocols/src/main/java/io/helidon/examples/webserver/protocols/ProtocolsMain.java
  examples/webserver/protocols/src/main/resources/certificate.p12
Labels: OCA Verified, 4.x
