Repository helidon-io/helidon-examples, pull requests merged in 2024-07, with the labels that each got.

#58 Exclude status example test for status 171 depending on JDK version
  examples/microprofile/http-status-count-mp/src/test/java/io/helidon/examples/mp/httpstatuscount/StatusTest.java
Labels: OCA Verified

#59 3.x backport stray fixes
  etc/scripts/updatehelidonversion.sh
  examples/microprofile/http-status-count-mp/src/test/java/io/helidon/examples/mp/httpstatuscount/StatusTest.java
Labels: OCA Verified, 3.x

#60 4.x: Update readmes to clarify use of dev-N.x branches for development
  CONTRIBUTING.md
  README.md
Labels: OCA Verified, 4.x

#61 [dev-4.x] Updates from the main Helidon repo
  examples/microprofile/cors/pom.xml
  examples/microprofile/static-content/pom.xml
  examples/security/basic-auth-with-static-content/src/test/java/io/helidon/examples/security/basicauth/BasicExampleTest.java
  examples/webserver/echo/src/main/java/io/helidon/examples/webserver/echo/EchoClient.java
  examples/webserver/tls/src/main/java/io/helidon/examples/webserver/tls/Main.java
Labels: OCA Verified, 4.x

#62 [4.x] Updates from the main Helidon repo
  examples/quickstarts/helidon-quickstart-se/pom.xml
  examples/quickstarts/helidon-quickstart-se/src/main/resources/logging.properties
Labels: OCA Verified, 4.x
