Repository helidon-io/helidon-examples, pull requests merged in 2024-12, with the labels that each got.

#105 2.x fix updatehelidonversion script
  etc/scripts/updatehelidonversion.sh
Labels: OCA Verified, 2.x

#106 3.x: fix updatehelidonversion script
  etc/scripts/updatehelidonversion.sh
Labels: OCA Verified, 3.x

#104 4.x: Change bind-address to host in socket configuration in multiport example
  examples/webserver/multiport/src/main/resources/application.yaml
Labels: OCA Verified, 4.x

#100 AQ messaging example update
  examples/dbclient/jdbc/src/main/java/io/helidon/examples/dbclient/jdbc/JdbcExampleMain.java
  examples/dbclient/jdbc/src/test/java/io/helidon/examples/dbclient/jdbc/AbstractPokemonServiceTest.java
  examples/dbclient/mongodb/src/main/java/io/helidon/examples/dbclient/mongo/MongoDbExampleMain.java
  examples/dbclient/mongodb/src/test/java/io/helidon/examples/dbclient/mongo/MainIT.java
  examples/dbclient/pokemons/src/main/java/io/helidon/examples/dbclient/pokemons/Main.java
  examples/dbclient/pokemons/src/test/java/io/helidon/examples/dbclient/pokemons/AbstractPokemonServiceTest.java
  examples/messaging/README.md
  examples/messaging/docker/oracle-aq-18-xe/buildAndRun.sh
  examples/messaging/docker/oracle-aq/Dockerfile
  examples/messaging/docker/oracle-aq/buildAndRun.sh
  examples/messaging/docker/oracle-aq/examples.sql
  examples/messaging/docker/oracle-aq/init.sql
  examples/messaging/oracle-aq-websocket-mp/pom.xml
  examples/messaging/oracle-aq-websocket-mp/src/main/java/io/helidon/examples/messaging/mp/MsgProcessingBean.java
  examples/messaging/oracle-aq-websocket-mp/src/main/resources/META-INF/microprofile-config.properties
  examples/messaging/oracle-aq-websocket-mp/src/main/resources/application.yaml
  examples/messaging/oracle-aq-websocket-mp/src/test/java/io/helidon/examples/messaging/mp/MessagingIT.java
  examples/messaging/oracle-aq-websocket-mp/src/test/java/io/helidon/examples/messaging/mp/MessagingTest.java
  examples/metrics/filtering/se/src/test/java/io/helidon/examples/metrics/filtering/se/MainTest.java
  examples/metrics/http-status-count-se/src/test/java/io/helidon/examples/se/httpstatuscount/MainTest.java
  examples/metrics/kpi/src/test/java/io/helidon/examples/metrics/kpi/MainTest.java
  examples/webserver/opentracing/src/main/java/io/helidon/examples/webserver/opentracing/Main.java
  examples/webserver/opentracing/src/test/java/io/helidon/examples/webserver/opentracing/MainTest.java
Labels: OCA Verified

#74 LRA testing feature #8469
  examples/integrations/cdi/pokemons/pom.xml
  examples/integrations/cdi/pokemons/src/main/resources/logging.properties
  examples/integrations/cdi/pokemons/src/test/java/io/helidon/examples/integrations/cdi/pokemon/MainTest.java
  examples/microprofile/lra/pom.xml
  examples/microprofile/lra/src/test/java/io/helidon/microprofile/example/lra/LRAExampleResourceTest.java
Labels: OCA Verified
